"""Topic list for story generation."""

TOPIC_LIST = [
    # --- I. Hard Sciences & Theoretical Physics (1-80) ---
    "quantum chromodynamics and gluon interaction",
    "string theory and Calabi-Yau manifolds",
    "loop quantum gravity and spin networks",
    "dark matter candidates and WIMPs",
    "Hawking radiation and black hole thermodynamics",
    "superconductivity and Cooper pairs",
    "particle physics and muon g-2 anomaly",
    "Bose-Einstein condensates and superfluidity",
    "general relativity and frame-dragging",
    "stellar nucleosynthesis in red giants",
    "galactic evolution and quasar feedback",
    "cosmic microwave background anisotropies",
    "neutrino oscillations and mass hierarchy",
    "plasma physics and magnetohydrodynamics",
    "nuclear fission in molten salt reactors",
    "optical lattices and ultracold atoms",
    "quantum entanglement and Bell's theorem",
    "topological insulators and Weyl semimetals",
    "Higgs field and spontaneous symmetry breaking",
    "special relativity and Lorentz transformation",
    "computational fluid dynamics in supersonic regimes",
    "chaos theory and strange attractors",
    "thermodynamics of non-equilibrium systems",
    "molecular orbital theory and hybridization",
    "organic chemistry of electrophilic substitution",
    "organometallic catalysts and ligands",
    "spectroscopy of infrared vibrational modes",
    "crystallography and Bravais lattices",
    "radioactive decay chains and half-life",
    "biophysics of protein folding kinetics",
    "enzymatic catalysis and Michaelis-Menten kinetics",
    "genomics of transposons and retroviruses",
    "electromagnetism and displacement current",
    "semiconductor physics and P-N junctions",
    "solid state physics and Phonon dispersion",
    "acoustics of wave interference and diffraction",
    "optics of nonlinear Kerr effect",
    "geophysics of mantle convection currents",
    "seismology of P-wave and S-wave shadows",
    "paleomagnetism and polarity reversals",
    "atmospheric chemistry of ozone depletion",
    "climatology of Milankovitch cycles",
    "oceanography of thermohaline circulation",
    "limnology of eutrophication processes",
    "volcanology of rhyolitic magma viscosity",
    "petrology of metamorphic facies",
    "stratigraphy of unconformities and biozones",
    "mineralogy of twinning and cleavage",
    "glaciology of ice shelf calving",
    "ecology of nitrogen fixation cycles",
    # --- II. Medicine, Biology & Pharmacology (81-160) ---
    "neuroanatomy of the basal ganglia",
    "synaptic plasticity and long-term potentiation",
    "immunology of MHC class I presentation",
    "cardiology of ventricular fibrillation",
    "endocrinology of hypothalamic-pituitary axis",
    "pharmacokinetics of first-pass metabolism",
    "pharmacodynamics of G-protein coupled receptors",
    "oncology of proto-oncogene activation",
    "virology of RNA-dependent RNA polymerase",
    "bacteriology of peptidoglycan synthesis",
    "hematology of hemoglobinopathy and sickle cell",
    "nephrology of glomerular filtration rate",
    "pulmonology of alveolo-capillary diffusion",
    "gastroenterology of bile acid enterohepatic circulation",
    "histopathology of squamous cell carcinoma",
    "dermatology of keratinocyte differentiation",
    "ophthalmology of retinal phototransduction",
    "otolaryngology of cochlear hair cell signaling",
    "orthopedics of osteoblast and osteoclast balance",
    "pediatrics of congenital heart defects",
    "obstetrics of pre-eclampsia pathophysiology",
    "urology of nephrolithiasis composition",
    "toxicology of organophosphate poisoning",
    "epidemiology of R0 reproduction numbers",
    "radiology of T1 and T2 relaxation in MRI",
    "anesthesiology of GABA receptor modulation",
    "psychiatry of dopamine hypothesis in schizophrenia",
    "rheumatology of synovial inflammation",
    "angiogenesis in tumor microenvironments",
    "epigenetics of histone acetylation",
    "microbiology of CRISPR-Cas9 defense",
    "genetics of mitochondrial inheritance",
    "human anatomy of the brachial plexus",
    "physiology of the renin-angiotensin system",
    "biotechnology of monoclonal antibody production",
    "stem cell differentiation and pluripotency",
    "parasitology of Plasmodium life cycles",
    "virology of antigenic drift vs shift",
    "surgical techniques for aortic aneurysm repair",
    "intensive care of septic shock protocols",
    # --- III. Advanced Engineering & Technology (161-240) ---
    "aerodynamics of boundary layer separation",
    "structural engineering of truss-frame bridges",
    "mechanical engineering of planetary gear sets",
    "civil engineering of soil liquefaction",
    "aerospace engineering of ion thrusters",
    "robotics of inverse kinematics solvers",
    "nanotechnology of carbon nanotubes and graphene",
    "materials science of fatigue and creep",
    "electrical engineering of three-phase power",
    "chemical engineering of distillation columns",
    "nuclear engineering of fuel rod cladding",
    "hydraulics of cavitation in centrifugal pumps",
    "automotive engineering of dual-clutch transmissions",
    "renewable energy grid stabilization",
    "marine engineering of cavitation-resistant propellers",
    "textile engineering of polymer extrusion",
    "acoustic engineering of anechoic chambers",
    "optical engineering of fiber bragg gratings",
    "petroleum engineering of hydraulic fracturing",
    "mining engineering of open-pit slope stability",
    "manufacturing engineering of six-sigma protocols",
    "metallurgy of martensitic transformation",
    "thermodynamics of Rankine and Brayton cycles",
    "control systems of PID loop tuning",
    "biomedical engineering of neural implants",
    "mechatronics of brushless DC motors",
    "geotechnical engineering of retaining walls",
    "urban engineering of sewage treatment plants",
    "architecture of parametric facade design",
    "industrial design of ergonomic interfaces",
    # --- IV. Software, AI & Cybersecurity (241-320) ---
    "software architecture of event-driven microservices",
    "low-level memory allocation in C++",
    "garbage collection in the Java Virtual Machine",
    "asynchronous I/O and event loops",
    "database internals of B+ trees and LSM trees",
    "distributed systems and Raft consensus",
    "cryptography of zero-knowledge proofs",
    "blockchain smart contract vulnerabilities",
    "cybersecurity of heap buffer overflows",
    "penetration testing of lateral movement",
    "machine learning of transformer self-attention",
    "neural network backpropagation algorithms",
    "natural language processing of word embeddings",
    "computer vision of convolutional kernels",
    "reinforcement learning and Q-learning",
    "generative AI and diffusion models",
    "cloud computing of multi-tenant isolation",
    "networking of BGP prefix hijacking",
    "operating system kernel interrupt handling",
    "compiler design of abstract syntax trees",
    "web development of shadow DOM and components",
    "frontend state management with Redux",
    "functional programming of monads and functors",
    "Rust ownership and borrowing system",
    "DevOps automation and CI/CD pipelines",
    "Kubernetes pod scheduling and affinity",
    "software testing of unit vs integration",
    "big data processing with Apache Spark",
    "internet of things and MQTT protocols",
    "hardware virtualization and VT-x",
    "firmware exploitation and UEFI security",
    "digital forensics of NTFS file systems",
    "API design of REST vs gRPC protocols",
    "graph database traversal algorithms",
    "search engine optimization and PageRank",
    "ui/ux design of cognitive load reduction",
    # --- V. Law, Finance & Corporate (321-400) ---
    "maritime law and general average",
    "intellectual property and patent claims",
    "corporate law and piercing the veil",
    "securities law and insider trading",
    "contract law and promissory estoppel",
    "tort law and vicarious liability",
    "employment law and constructive dismissal",
    "tax law and transfer pricing",
    "bankruptcy law and preferential transfers",
    "international law and jus cogens",
    "criminal law and mens rea vs actus reus",
    "environmental law and carbon credits",
    "commercial law and negotiable instruments",
    "real estate law and easements",
    "insurance law and subrogation clauses",
    "family law and equitable distribution",
    "investment banking of leveraged buyouts",
    "venture capital of liquidation preferences",
    "mergers and acquisitions of hostile takeovers",
    "finance of Black-Scholes model",
    "macroeconomics of liquidity traps",
    "microeconomics of marginal utility",
    "behavioral economics and loss aversion",
    "stock market of technical analysis",
    "accounting of revenue recognition principles",
    "auditing of internal control frameworks",
    "logistics of just-in-time manufacturing",
    "supply chain of bullwhip effect",
    "marketing of brand equity and positioning",
    "human resources of 360-degree feedback",
    # --- VI. History, Culture & Arts (401-480) ---
    "Renaissance art and chiaroscuro techniques",
    "Baroque music and figured bass",
    "Romanticism in literature and the sublime",
    "Modernism and stream of consciousness",
    "Postmodernism and hyperreality in media",
    "Ancient Egyptian funerary architecture",
    "Greek philosophy of Platonic forms",
    "Roman history of the Punic Wars",
    "Medieval feudalism and the manorial system",
    "Napoleonic era military logistics",
    "Industrial Revolution and urbanization",
    "Cold War espionage and signal intel",
    "Victorian era social stratification",
    "Impressionist painting and light capture",
    "Cinema history of Soviet montage theory",
    "Photography of the zone system",
    "Fashion history of haute couture draping",
    "Culinary history of the spice trade",
    "Linguistics of Indo-European phonology",
    "Anthropology of kinship structures",
    "Sociology of social capital and habitus",
    "Archaeology of the Hellenistic period",
    "Mythology of the monomyth cycle",
    "Music theory of polyphonic counterpoint",
    "Theology of the scholastic movement",
    "History of the Silk Road trade",
    "Orientalism in Western literature",
    "Feminist theory and the male gaze",
    # --- VII. Niche Crafts, Hobbies & Industry (481-520) ---
    "apiculture and varroa mite management",
    "oenology of malolactic fermentation",
    "horology of tourbillon escapements",
    "numismatics of strike errors and dies",
    "vexillology of flag heraldry rules",
    "gardening of permaculture guilds",
    "woodworking of dovetail joinery",
    "blacksmithing of pattern welding",
    "ceramic engineering of glaze chemistry",
    "aquarium keeping of nitrogen cycles",
    "model railroading of DCC wiring",
    "ham radio of ionospheric propagation",
    "survivalism of primitive fire making",
    "homesteading of livestock rotation",
    "culinary arts of sous-vide precision",
    "coffee roasting of Maillard reaction",
    "watchmaking of hairspring adjustment",
    "textile arts of jacquard weaving",
    "brewing of hop alpha acid isomerization",
    "distilling of fractional reflux",
    # --- VIII. Wikipedia Main Knowledge Classifications (521-600+) ---
    # Culture and the Arts
    "contemporary performance art",
    "ethnomusicology and folk traditions",
    "literary realism vs romanticism",
    "sculpture techniques in bronze and marble",
    "history of global cinema",
    "architectural preservation and heritage",
    # Geography and Places
    "cartography and GIS mapping",
    "geopolitics of the Arctic Circle",
    "urbanization in Southeast Asia",
    "climatology of tropical rainforests",
    "demographics and migration patterns",
    "topography of the Andes mountains",
    # Health and Fitness
    "public health surveillance systems",
    "nutrition and metabolic syndrome",
    "preventive medicine and wellness",
    "epidemiology of non-communicable diseases",
    "mental health and psychotherapy models",
    "sports physiology and endurance",
    # History and Events
    "historiography and primary source analysis",
    "history of the Mongol Empire",
    "The Great Depression's global impact",
    "decolonization of Africa in the 20th century",
    "the Silk Road's cultural exchange",
    "maritime exploration in the Age of Discovery",
    # Mathematics and Logic
    "set theory and cardinal numbers",
    "abstract algebra and group theory",
    "probability theory and Bayesian inference",
    "topology and manifold classification",
    "mathematical analysis and limits",
    "cryptographic number theory",
    # Natural and Physical Sciences
    "evolutionary developmental biology (Evo-Devo)",
    "theoretical particle physics",
    "ecology of invasive species",
    "geology of the Precambrian era",
    "organic chemistry and chirality",
    "quantum field theory",
    # People and Self
    "cognitive development in early childhood",
    "social psychology and groupthink",
    "theories of personality and identity",
    "human sexuality and gender studies",
    "philosophy of the self and consciousness",
    "biographies of revolutionary scientists",
    # Philosophy and Thinking
    "epistemology and the nature of truth",
    "deontology vs consequentialism",
    "phenomenology and lived experience",
    "philosophy of science and falsifiability",
    "existentialist ethics and freedom",
    "logic and formal syllogisms",
    # Reference and Research
    "library science and information taxonomies",
    "research methodology and peer review",
    "citation analysis and h-index",
    "archival science and document preservation",
    "statistics in social sciences",
    "lexicography and dictionary construction",
    # Religion and Belief Systems
    "comparative theology and eschatology",
    "history of Zen Buddhism",
    "mythology of the Norse gods",
    "sociology of religious institutions",
    "mysticism and monastic traditions",
    "interfaith dialogue and secularism",
    # Social Sciences and Society
    "political science and voting systems",
    "anthropology of ritual and taboo",
    "sociology of urban stratification",
    "jurisprudence and legal theory",
    "international relations and diplomacy",
    # Technology and Applied Sciences
    "civil engineering and infrastructure",
    "biotechnology and genetic engineering",
    "nanomaterials and thin-film deposition",
    "renewable energy and solar photovoltaics",
    "telecommunications and 6G development",
    "robotics and artificial intelligence ethics",
    # --- Életmód, Család & Kapcsolatok (1-100) ---
    "parenting styles and child development",
    "the psychology of long-distance relationships",
    "balancing career and family life",
    "the impact of social media on teenage self-esteem",
    "coping with grief and bereavement",
    "the dynamics of modern blended families",
    "friendship in the digital age",
    "conflict resolution in marriage",
    "the importance of early childhood education",
    "caring for aging parents and elderly law",
    "wedding traditions across different cultures",
    "the role of godparents in society",
    "adoption processes and emotional challenges",
    "single parenthood and support networks",
    "the evolution of dating apps",
    "household budgeting and financial literacy",
    "minimalist living and decluttering",
    "the art of hosting and hospitality",
    "pet ownership and mental well-being",
    "mentorship and its role in personal growth",
    "the ethics of homeschooling",
    "overcoming loneliness in urban environments",
    "the psychology of attraction",
    "attachment theory in adult relationships",
    "sibling rivalry and lifelong bonds",
    "celebrating cultural holidays and festivals",
    "the impact of divorce on children",
    "intergenerational trauma and healing",
    "finding work-life harmony",
    "the concept of 'ikigai' and purpose",
    # --- Munka, Karrier & Gazdaság (101-200) ---
    "the future of remote work and telecommuting",
    "overcoming burnout and workplace stress",
    "the gender pay gap and economic equity",
    "entrepreneurship and startup culture",
    "the gig economy and freelancer rights",
    "soft skills vs hard skills in the 21st century",
    "workplace diversity and inclusion initiatives",
    "the ethics of corporate lobbying",
    "investing in the stock market for beginners",
    "the rise of sustainable and ethical investing",
    "career pivoting in mid-life",
    "the impact of AI on job security",
    "effective leadership and team building",
    "negotiation tactics for salary increases",
    "the history of labor unions",
    "urban commuting and public transport",
    "the psychology of consumerism",
    "fast fashion vs sustainable clothing",
    "the gig economy's impact on local business",
    "cryptocurrency as a personal investment",
    "real estate flipping and housing markets",
    "the sociology of the middle class",
    "poverty alleviation strategies",
    "the future of universal basic income",
    "time management hacks for productivity",
    "the art of public speaking",
    "networking for introverts",
    "business etiquette in international trade",
    "the psychology of sales and persuasion",
    "workplace ergonomics and physical health",
    # --- Egészség, Wellness & Pszichológia (201-300) ---
    "mindfulness and meditation for anxiety",
    "the benefits of a plant-based diet",
    "overcoming insomnia and sleep disorders",
    "the psychology of habit formation",
    "the impact of sugar on long-term health",
    "intermittent fasting and metabolism",
    "mental health stigma in different cultures",
    "the importance of gut health and probiotics",
    "chronic pain management and therapy",
    "the benefits of outdoor exercise and nature",
    "understanding neurodiversity (ADHD, Autism)",
    "the science of happiness and gratitude",
    "addiction recovery and support systems",
    "the ethics of plastic surgery",
    "biohacking and human enhancement",
    "the rise of telemedicine",
    "holistic vs traditional medicine",
    "coping with social anxiety",
    "the benefits of yoga and flexibility",
    "the impact of screen time on eye health",
    "understanding the placebo effect",
    "the psychology of resilience",
    "eating disorders and body positivity",
    "the benefits of art therapy",
    "the science of longevity and aging well",
    "preventive healthcare and regular checkups",
    "the role of supplements in nutrition",
    "the impact of noise pollution on stress",
    "the importance of hydration",
    # --- Társadalom, Politika & Aktuális ügyek (301-400) ---
    "climate change activism and grassroots movements",
    "the ethics of data privacy and surveillance",
    "immigration policies and refugee integration",
    "the rise of populism in modern politics",
    "freedom of speech vs hate speech",
    "the impact of fake news on democracy",
    "urban planning and walkable cities",
    "the future of space exploration and colonization",
    "animal rights and welfare legislation",
    "the role of the UN in global conflicts",
    "social justice and systemic inequality",
    "the ethics of genetic engineering in humans",
    "renewable energy vs fossil fuel subsidies",
    "the impact of tourism on local cultures",
    "voting rights and electoral integrity",
    "the prison-industrial complex",
    "gun control debates and public safety",
    "the legalization of medicinal cannabis",
    "the future of education and online learning",
    "water scarcity and global security",
    "the impact of inflation on daily life",
    "the ethics of artificial intelligence in warfare",
    "human rights in the digital age",
    "the role of investigative journalism",
    "public housing and homelessness solutions",
    "cultural appropriation vs appreciation",
    "the impact of globalization on local languages",
    # --- Szórakozás, Szabadidő & Hobbi (401-500) ---
    "the evolution of video game storytelling",
    "the impact of streaming services on cinema",
    "traveling on a budget: tips and tricks",
    "the rise of true crime podcasts",
    "the history and future of board games",
    "gardening for city dwellers: balcony plants",
    "the art of photography in the smartphone era",
    "DIY home renovation projects",
    "the psychology of fandom and stan culture",
    "collecting vinyl records in a digital world",
    "the benefits of learning a second language",
    "the history of olympic sports",
    "amateur astronomy and stargazing",
    "the world of competitive esports",
    "cooking as a form of creative expression",
    "the art of calligraphy and hand-lettering",
    "birdwatching and citizen science",
    "the rise of van life and nomadic living",
    "the ethics of zoos and wildlife parks",
    "the future of live music and concerts",
    "recreational hiking and trail safety",
    "the history of stand-up comedy",
    # --- Korábbi tudományos kategóriák ---
    "quantum chromodynamics",
    "molecular biology",
    "orbital mechanics",
    "maritime law",
    "asynchronous programming",
    "existentialist philosophy",
    "haute couture",
    # --- Wikipedia fő kategóriák ---
    "epistemology",
    "historiography",
    "cartography",
    "comparative theology",
    "eschatology",
    "jurisprudence",
    # --- A te listád: Mindennapi rutinok & Otthon ---
    "morning and evening routines",
    "household chores and cleaning",
    "organizing and decluttering",
    "home maintenance and HVAC repair",
    "plumbing and electrical troubleshooting",
    "interior design and furniture shopping",
    "moving and packing logistics",
    "smart home automation and security cameras",
    "landscaping and lawn care",
    "shoveling snow and gutter cleaning",
    "laundry and dry cleaning services",
    # --- Étel, Ital & Gasztronómia ---
    "meal planning and grocery shopping",
    "baking and cookie decorating",
    "grilling and outdoor barbecues",
    "dining out vs takeout delivery",
    "coffee culture: espresso and cold brew",
    "tea varieties: matcha and chai",
    "smoothies and protein shakes",
    "wine making and home brewing",
    "fermentation: sourdough and pickling",
    "canning and freeze-drying",
    # --- Közlekedés & Utazás ---
    "commuting: rush hour and traffic",
    "public transport: subways and buses",
    "car maintenance: oil changes and tire rotations",
    "electric vehicle charging networks",
    "road trips and national park camping",
    "air travel: TSA security and boarding",
    "Frequent flyer programs and status tiers",
    "travel insurance and medical evacuation",
    "kayaking, canoeing, and paddleboarding",
    "cycling and electric scooters",
    # --- Munka, Karrier & Pénzügy ---
    "job interviews and salary negotiation",
    "remote work and coworking spaces",
    "freelancing and side hustles",
    "office politics and team building",
    "budgeting apps and expense tracking",
    "retirement planning: 401k and IRA",
    "investing: stocks, bonds, and cryptocurrency",
    "mortgages and real estate law",
    "taxes: preparation and accountants",
    "insurance: health, life, and car policies",
    # --- Egészség & Wellness ---
    "gym memberships and personal trainers",
    "yoga, pilates, and spin classes",
    "meditation and mental health therapy",
    "sleep habits and insomnia treatment",
    "dental hygiene and specialists",
    "pharmacy and medication management",
    "keto, paleo, and vegan diets",
    "first aid and emergency triage",
    "skincare routines and dermatology",
    "spa days and aromatherapy",
    # --- Szórakozás & Technológia ---
    "streaming services: Netflix and Disney+",
    "video games: PC vs console gaming",
    "social media: TikTok, Instagram, and Reddit",
    "podcasts: true crime and comedy",
    "audiobooks and e-books",
    "photography and unboxing videos",
    "live concerts and theater performances",
    "museums and art galleries",
    "smartphones: iOS vs Android ecosystems",
    "cybersecurity: VPNs and data breaches",
    # --- Kapcsolatok & Társadalom ---
    "parenting: teenagers and elderly care",
    "dating, marriage, and divorce",
    "community volunteering and charity",
    "religion and spirituality: prayer and temples",
    "holidays: Christmas, Hanukkah, and Ramadan",
    "celebrations: weddings and anniversaries",
    "graduation and career changes",
    "intergenerational living and caregiving",
    # --- Hobbi & Kreativitás ---
    "scrapbooking and journaling",
    "woodworking and metalworking",
    "knitting, sewing, and leatherworking",
    "pottery and glassblowing",
    "drawing, painting, and digital art",
    "escape rooms and murder mystery parties",
    "tabletop RPGs and board game nights",
    "gardening: plant care and fertilizing",
    # --- Speciális & Niche (A te listád vége) ---
    "skateboarding culture and skate parks",
    "DIY tools: saws, drills, and impact drivers",
    "electrical wiring and circuit testers",
    "emergency radios and ham radio",
    "solar panels and power banks",
    "battery degradation and vehicle-to-grid tech",
    "minimalism: Marie Kondo and simple living",
    "Scandinavian concepts: Hygge and Lagom",
    "Japanese concepts: Ikigai and Wabi-sabi",
    "subscription boxes and meal kits",
    "package theft and porch pirates",
    "virtual reality: Oculus and Metaverse",
    "coding bootcamps and online certifications",
    "site reliability engineering and chaos engineering",
]

STYLE_MODIFIERS = [
    "encyclopedic Wikipedia style", "informal blog post tone",
    "highly technical white paper", "emotional personal diary entry",
    "professional legal/corporate briefing", "casual Reddit-style discussion",
    "descriptive narrative style", "step-by-step tutorial instructional tone"
]